### ISSUE TITLE
Error in masking

### ISSUE THREAD

**Issue by LudoPoire** [rrwick/Verticall#6]
Hello @rrwick and team, 
I'm having trouble when masking recombination regions in an alignment of ~370 bacterial genomes, generated with snippy.
The alignment itself looks good, with all the sequences displayed as such :
>Reference
ACTGACTG...
>Strain_1
ACT--CTN...
And I can run the first step (pairwise alignment) with no problem. It generates a file (pairwise.tsv) which doesn't have any info about the length of the reference sequence.

The problem is, when I try to run the 2nd step (mask), I get this error : 

Starting Verticall mask
    Verticall mask uses the results from Verticall pairwise to mask horizontal regions from a whole-genome pseudo-alignment.

Input pairwise tsv:      pairwise.tsv
Input pseudo-alignment:  ../snippy/new_clean.full.aln
Output masked alignment: verticall_mask.fasta

Loading input data
pairwise.tsv:
  Automatically determined reference name: (my ref strain)
  369 reference-to-assembly pairwise comparisons
  Reference length: 3,767,949 bp

../snippy/new_clean.full.aln:
  371 sequences loaded
  Pseudo-alignment length: 3,767,949 bp

369 sample names are common to both tsv and pseudo-alignment files

Masking sequences
Error: length of reference sequence in alignment does not match length of reference sequence in TSV file - have regions been masked with dashes?

I'd like some help on how to fix this, please.

Thanks !

Ludo

**Comment by LudoPoire** [comment]
Thanks for the quick answer !

I found the solution, the alignment file (which was generated with [snippy](https://github.com/tseemann/snippy)) was formatted wrong : the first sequence in the file was not the reference I had used, but some random other sequence (so it had gaps and Ns as it was aligned against the reference).
If anyone runs into this issue, verify the format of the alignment file as it can be generated wrong !

**Comment by rrwick** [comment]
Glad you figured it out!
